<?php
############################################################
#######                                             ########
#######                                             ########
#######           malucos-share.org 2.0             ########
#######                                             ########
#######                                             ########
############################################################
error_reporting(E_ALL ^ E_NOTICE);
require_once("config.php");  

$smilies = array(
":alien" => "alien.gif",
":angel" => "angel.gif",
":angry" => "angry.gif",
":arrow" => "arrow.gif",
":axe" => "axe.gif",
":baby" => "baby.gif",
":banana" => "banana.gif",
":bandana" => "bandana.gif",
":bangin" => "bangin.gif",
":beer" => "beer.gif",
":ber2" => "beer2.gif",
":blush" => "blush.gif",
":book" => "book.gif",
":boude" => "boude.gif",
":bounce" => "bounce.gif",
":box" => "box.gif",
":bo_xing " => "boxing.gif",
":buz" => "buz.gif",
":cake" => "cake.gif",
":cap" => "cap.gif",
":chef" => "chef.gif",
":cigar" => "cigar.gif",
":closedeyes" => "closedeyes.gif",
":clover" => "clover.gif",
":confused" => "confused.gif",
":console" => "console.gif",
":cool1" => "cool1.gif",
":cool2" => "cool2.gif",
":cowboy" => "cowboy.gif",
":crazy" => "crazy.gif",
":crokett" => "crokett.gif",
":cry" => "cry.gif",
":deadhorse" => "deadhorse.gif",
":devil" => "devil.gif",
":dots" => "dots.gif",
":drunk" => "drunk.gif",
":dumbells" => "dumbells.gif",
":evil" => "evil.gif",
":evi_lmad" => "evilmad.gif",
":evo" => "evo.gif",
":excl" => "excl.gif",
":fez" => "fez.gif",
":fun" => "fun.gif",
":gdn" => "gdn.gif",
":geek" => "geek.gif",
":greedy" => "greedy.gif",
":grin" => "grin.gif",
":group" => "group.gif",
":guns" => "guns.gif",
":hannibal" => "hannibal.gif",
":happy" => "happy.gif",
":hbd" => "hbd.gif",
":hi" => "hi.gif",
":hmm" => "hmm.gif",
":hooray" => "hooray.gif",
":huh" => "huh.gif",
":hump" => "hump.gif",
":icecream" => "icecream.gif",
":idea" => "idea.gif",
":ike" => "ike.gif",
":indian" => "indian.gif",
":jacko" => "jacko.gif",
":judge" => "judge.gif",
":king" => "king.gif",
":kiss" => "kiss.gif",
":kuku" => "kuku.gif",
":laugh" => "laugh.gif",
":lmfao" => "lmfao.gif",
":look" => "look.gif",
":love" => "love.gif",
":lo_vers" => "lovers.gif",
":mama" => "mama.gif",
":mario" => "mario.gif",
":medieval" => "medieval.gif",
":music" => "music.gif",
":ninja" => "ninja.gif",
":no" => "no.gif",
":n_oexpression" => "noexpression.gif",
":_nono" => "nono.gif",
":nugget" => "nugget.gif",
":nuke" => "nuke.gif",
":ohmy" => "ohmy.gif",
":oldtimer" => "oldtimer.gif",
":oops" => "oops.gif",
":osama" => "osama.gif",
":party" => "party.gif",
":p_artytw6" => "partytw6.gif",
":pepsi" => "pepsi.gif",
":pimp" => "pimp.gif",
":pirate" => "pirate.gif",
":pope" => "pope.gif",
":powerb" => "powerb.gif",
":protest" => "protest.gif",
":punk" => "punk.gif",
":question" => "question.gif",
":rambo" => "rambo.gif",
":rant" => "rant.gif",
":ras" => "ras.gif",
":retro2" => "retro2.gif",
":rip" => "rip.gif",
":rock" => "rock.gif",
":rolleyes" => "rolleyes.gif",
":sad" => "sad.gif",
":s_addam" => "saddam.gif",
":santa" => "santa.gif",
":searching" => "searching.gif",
":sheep" => "sheep.gif",
":shifty" => "shifty.gif",
":_shit" => "cobra.gif",
":shoot" => "shoot.gif",
":shutup" => "shutup.gif",
":s_hutup2" => "shutup2.gif",
":sick" => "sick.gif",
":s_lap1" => "slap1.gif",
":sleep" => "sleep.gif",
":s_leeping" => "sleeping.gif",
":sly" => "sly.gif",
":smart" => "smart.gif",
":s_martass" => "smartass.gif",
":smile1" => "smile1.gif",
":smile2" => "smile2.gif",
":smurf" => "smurf.gif",
":snack" => "snack.gif",
":snap" => "snap.gif",
":sneaky" => "sneaky.gif",
":snorkle" => "snorkle.gif",
":spank" => "spank.gif",
":spidey" => "spidey.gif",
":strongbench" => "strongbench.gif",
":super" => "super.gif",
":thankyou" => "thankyou.gif",
":thumbsdown" => "thumbsdown.gif",
":thumbsup" => "thumbsup.gif",
":tongue" => "tongue.gif",
":train" => "train.gif",
":unsure" => "unsure.gif",
":w00t" => "w00t.gif",
":wacko" => "wacko.gif",
":wall" => "wall.gif",
":wave" => "wave.gif",
":w_avecry" => "wavecry.gif",
":weakbench" => "weakbench.gif",
":weep" => "weep.gif",
":welcome-back" => "welcome-back.gif",
":whistle" => "whistle.gif",
":wizzard" => "wizzard.gif",
":wolverine" => "wolverine.gif",
":wub" => "wub.gif",
":love_wub" => "love_wub.gif",
":yahoo" => "yahoo.gif",
":yes" => "yes.gif",
":yikes" => "yikes.gif",
":yu" => "yu.gif",
":y_ucky" => "yucky.gif",
":zorro" => "zorro.gif",
":angry" => "angry.gif",
":blink" => "blink.gif",
":blush" => "blush.gif",
":confused" => "confused.gif",
":cry" => "cry.gif",
":yes" => "yes.gif",
":no" => "no.gif",
":dry" => "dry.gif",
":evil" => "evil.gif",
":excl" => "excl.gif",
":grin" => "grin.gif",
":laugh" => "laugh.gif",
":lmfao" => "lmfao.gif",
":look" => "look.gif",
":love" => "love.gif",
":noexpression" => "noexpression.gif",
":sleep" => "sleep.gif",
":smile1" => "smile1.gif",
":thumbsup" => "thumbsup.gif",
":weep" => "weep.gif",
":wink" => "wink.gif",
":wub" => "wub.gif",
":yahoo" => "yahoo.gif",
":love_wub" => "love_wub.gif",
);

function insert_smilies_frame () {
	GLOBAL $site_config, $smilies;

	echo "<table><tr><td class=\"colhead\">Type...</td><td class=\"colhead\">To make a...</td></tr>";
	foreach ($smilies as $code => $url) {
		echo "<tr><td>$code</td><td><a href=\"javascript:window.opener.SmileIT('$code', '".htmlspecialchars($_GET[form])."', '".htmlspecialchars($_GET[text])."')\"><img src=\"$site_config[SITEURL]/images/smilies/$url\" alt=\"$code\" title=\"$code\" border=\"0\"></a></td></tr>";
	}
	echo "</table>";
}

if ($_GET['action'] == "display"){
	insert_smilies_frame();
}

?>